# Generated by Django 3.0.1 on 2019-12-29 12:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
import maps.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('created', models.DateField(default=datetime.datetime.now)),
                ('modified', models.DateField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('game', models.CharField(choices=[('q1', 'Quake 1'), ('q2', 'Quake 2'), ('q3', 'Quake 3')], default='q1', max_length=2)),
                ('homepage', models.URLField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MapPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(unique=True, upload_to=maps.models.mappackage_upload_to)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('maps', models.ManyToManyField(related_name='tags', to='maps.Map')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=maps.models.map_screenshot_path)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='maps.Map')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='maps.Map')),
            ],
        ),
        migrations.CreateModel(
            name='MapUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url', models.URLField()),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='maps.Map')),
            ],
        ),
        migrations.CreateModel(
            name='MapFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('size', models.IntegerField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='maps.Map')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='map',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.MapPackage'),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=64, null=True)),
                ('homepage', models.URLField(blank=True, null=True)),
                ('maps', models.ManyToManyField(related_name='authors', to='maps.Map')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
