# Generated by Django 3.0.1 on 2019-12-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='maps',
        ),
        migrations.AddField(
            model_name='map',
            name='tags',
            field=models.ManyToManyField(related_name='maps', to='maps.Tag'),
        ),
    ]
