# Generated by Django 3.0.1 on 2019-12-29 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20191229_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('skill', models.IntegerField(choices=[(0, 'Easy'), (1, 'Normal'), (2, 'Hard'), (3, 'Nightmware')], default=1)),
                ('length', models.IntegerField()),
                ('protocol', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.MapPackage')),
            ],
        ),
    ]
