# Generated by Django 3.0.1 on 2019-12-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_demo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='protocol',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
