# Generated by Django 3.0.1 on 2019-12-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_auto_20191229_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='maps',
            field=models.ManyToManyField(to='maps.Map'),
        ),
    ]
