# Generated by Django 3.0.1 on 2019-12-30 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_auto_20191230_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='submit_date',
            field=models.DateTimeField(db_index=True, default=None),
        ),
        migrations.AlterField(
            model_name='comment',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='maps.Map'),
        ),
    ]
