# Generated by Django 3.0.1 on 2019-12-30 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_auto_20191230_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='package',
        ),
        migrations.AddField(
            model_name='mappackage',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='maps.Map'),
        ),
    ]
