# Generated by Django 3.0.1 on 2019-12-31 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_auto_20191230_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mappackage',
            old_name='hash',
            new_name='file_hash',
        ),
        migrations.RenameField(
            model_name='mappackage',
            old_name='name',
            new_name='file_name',
        ),
    ]
