# Generated by Django 3.0.1 on 2019-12-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_auto_20191231_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='maps',
            field=models.ManyToManyField(related_name='tags', to='maps.Map'),
        ),
    ]
