# Generated by Django 3.0.1 on 2019-12-31 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0011_auto_20191231_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='submit_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
