# Generated by Django 3.0.1 on 2019-12-31 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0012_auto_20191231_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_name',
            new_name='name',
        ),
    ]
