# Generated by Django 3.0.1 on 2019-12-31 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0013_auto_20191231_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='map',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='CommentFlag',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
