# Generated by Django 3.0.1 on 2019-12-31 15:44

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('maps', '0014_auto_20191231_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='taggits',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
