# Generated by Django 3.0.3 on 2020-02-29 06:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import quaddicted.packages.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=256, upload_to=quaddicted.packages.models.package_upload_to, validators=[quaddicted.packages.models.validate_package_file])),
                ('file_name', models.CharField(blank=True, editable=False, max_length=128)),
                ('file_hash', models.CharField(blank=True, editable=False, max_length=64, unique=True)),
                ('file_size', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=128)),
                ('created', models.DateField(auto_now_add=True)),
                ('rating', models.FloatField(blank=True, editable=False, null=True)),
                ('game', models.CharField(choices=[('q1', 'Quake 1'), ('q2', 'Quake 2'), ('q3', 'Quake 3')], default='q1', max_length=2)),
                ('description', models.TextField(blank=True)),
                ('published', models.BooleanField(default=False)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='A 16x9 resolution image at least 1024x576', max_length=256, upload_to=quaddicted.packages.models.screenshot_upload_to)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='quaddicted_packages.Package')),
            ],
        ),
        migrations.CreateModel(
            name='PackageUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url', models.URLField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='quaddicted_packages.Package')),
            ],
        ),
        migrations.CreateModel(
            name='PackageAuthors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quaddicted_packages_packageauthors_tagged_items', to='contenttypes.ContentType', verbose_name='Content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quaddicted_packages_packageauthors_authors', to='quaddicted_packages.Author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='package',
            name='authors',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of authors.', through='quaddicted_packages.PackageAuthors', to='quaddicted_packages.Author', verbose_name='Authors'),
        ),
        migrations.AddField(
            model_name='package',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='package',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=256, upload_to='')),
                ('skill', models.IntegerField(choices=[(0, 'Easy'), (1, 'Normal'), (2, 'Hard'), (3, 'Nightmware')], default=1)),
                ('length', models.DurationField()),
                ('protocol', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField()),
                ('description', models.TextField(blank=True, max_length=512)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quaddicted_packages.Package')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=32, null=True)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='quaddicted_packages.Package')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'package'), ('username', 'package')},
            },
        ),
    ]
