# Generated by Django 3.1.1 on 2020-11-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quaddicted_packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='start_map',
            field=models.CharField(blank=True, help_text='which map should be loaded', max_length=64, null=True),
        ),
    ]
