# Generated by Django 3.1.1 on 2020-09-18 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangobb_forum', '0002_auto_20200918_1132'),
        ('quaddicted_packages', '0002_auto_20200913_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='topic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package', to='djangobb_forum.topic'),
        ),
    ]
