# Generated by Django 3.1.1 on 2020-11-03 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quaddicted_packages', '0002_package_start_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the map', max_length=64, null=True)),
                ('file_name', models.CharField(help_text='File name stem (no extension) of the map', max_length=64)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='quaddicted_packages.package')),
            ],
        ),
    ]
