# Generated by Django 3.1.1 on 2020-11-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quaddicted_packages', '0003_packagemap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='authors',
        ),
        migrations.AddField(
            model_name='packageauthor',
            name='packages',
            field=models.ManyToManyField(related_name='authors', to='quaddicted_packages.Package'),
        ),
    ]
