# Generated by Django 3.1.1 on 2020-11-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quaddicted_packages', '0004_auto_20201108_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageauthor',
            name='packages',
        ),
        migrations.AddField(
            model_name='package',
            name='authors',
            field=models.ManyToManyField(help_text='A comma-separated list of authors.', related_name='packages', to='quaddicted_packages.PackageAuthor'),
        ),
    ]
