# Generated by Django 3.1.1 on 2020-12-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quaddicted_packages', '0005_auto_20201108_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='authors',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='uploaded_on',
            new_name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='package',
            name='dependencies',
            field=models.ManyToManyField(blank=True, to='quaddicted_packages.Package'),
        ),
    ]
