# Generated by Django 3.1.1 on 2020-12-21 16:18

from django.db import migrations, models
import django.utils.timezone
import quaddicted.packages.models


class Migration(migrations.Migration):

    dependencies = [
        ('quaddicted_packages', '0006_auto_20201206_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='package',
            name='file',
            field=models.FileField(help_text='A zip file containing your Quake map or mod', max_length=256, upload_to=quaddicted.packages.models.package_upload_to, validators=[quaddicted.packages.models.validate_package_file]),
        ),
    ]
